### ISSUE TITLE
ROS2 Port?

### ISSUE THREAD

**Issue by hehateme1304** [MIT-REALM/architect#1]
Good afternoon,

thank you for posting this project.  My team and I were wondering is their any plans to port this to ROS2 in the future?  We currently have a ROS2 project in the works and was interested in applying this to see what optimizations it would enlighten us too.  We went thru codebase and saw that it was all in ROS1.  Was just curious on your teams thoughts?  I know ROS2 isnt super well documented quite yet so that makes it much more difficult.

**Comment by dawsonc** [comment]
Hi! Sorry for the delay in responding!

This project is actually quite agnostic to whether your code is in ROS1 or ROS2. The goal of `architect` is to optimize the parameters of your autonomous system; i.e. help you sort out things like control gains and sensor placements. As a result, it doesn't care how you implement your system (ROS1/ROS2), it just wants you to provide a simulator (ideally in an autodiff framework like JAX) for how your system works.

The ROS1 code in this repo is just to run some hardware experiments in our lab, and it's pretty separate from the core functionality of optimization/sensitivity estimation.
